layout_spectrum: 0.3356606
color:
  saturation: 0.6074114
  brandStrength: 0.8218006
  lightness: 0.6804512
  rhythmicContrast: 0.367884
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.5300752
name: Nick Carter Photography
