collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2518797
  brandStrength: 0.8218006
  lightness: 0.2303974
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.6578947
typography_spectrum: 0.5300752
layout_spectrum: 0.2207304
name: Nick Carter Photography
